import { StatusPill, type ContentStatusKey } from "@/components/StatusPill";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CalendarCheck2, CheckCircle2, ClipboardCheck, Send, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

const dateKey = (date: Date) => date.toISOString().slice(0, 10);
const localDateInput = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;

export default function Calendar() {
  const utils = trpc.useUtils();
  const contentQuery = trpc.content.list.useQuery();
  const [selectedId, setSelectedId] = useState("");
  const [scheduleDate, setScheduleDate] = useState(localDateInput(new Date()));
  const [publishId, setPublishId] = useState<number | null>(null);
  const [publishResult, setPublishResult] = useState("");
  const [publishUrl, setPublishUrl] = useState("");
  const schedule = trpc.content.schedule.useMutation({ onSuccess: () => { utils.content.list.invalidate(); utils.content.overview.invalidate(); toast.success("排期已写入日历"); }, onError: () => toast.error("请先选择内容和日期") });
  const markPublished = trpc.content.markPublished.useMutation({ onSuccess: () => { utils.content.list.invalidate(); utils.content.overview.invalidate(); utils.analytics.list.invalidate(); setPublishId(null); setPublishResult(""); setPublishUrl(""); toast.success("人工发布结果已记录"); }, onError: () => toast.error("记录失败，请检查链接格式") });
  const days = useMemo(() => Array.from({ length: 7 }, (_, index) => { const d = new Date(); d.setHours(0, 0, 0, 0); d.setDate(d.getDate() + index); return d; }), []);
  const scheduledItems = contentQuery.data?.filter(item => item.status === "scheduled" && item.scheduledAt) ?? [];
  const readyItems = contentQuery.data?.filter(item => item.status !== "published") ?? [];
  const selectedPublish = contentQuery.data?.find(item => item.id === publishId);

  if (contentQuery.isLoading) return <CalendarState title="正在铺开你的发布节奏" description="正在载入内容与发布排期。" />;
  if (contentQuery.error) return <CalendarState title="发布日历暂时未能载入" description="请检查网络后重试；已经确认的排期仍会保留。" retry={() => contentQuery.refetch()} />;

  return <div className="mx-auto max-w-7xl space-y-6"><header><p className="text-xs font-medium tracking-[0.18em] text-[#A56F61]">PUBLISHING COORDINATION</p><h1 className="mt-2 font-serif text-3xl text-[#403530]">发布日历</h1><p className="mt-2 text-sm text-[#82776E]">安排节奏、完成检查，并在你手动发布后留下真实的执行记录。</p></header>
    <section className="rounded-[1.5rem] border border-[#E9E1D9] bg-[#FFFDFC] p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-medium tracking-[0.15em] text-[#A49A91]">WEEKLY RHYTHM</p><h2 className="mt-1 font-serif text-xl text-[#413632]">未来七天</h2></div><div className="flex items-center gap-2 text-xs text-[#8A7E75]"><CalendarCheck2 className="h-4 w-4 text-[#B26D5B]" />仅作排期与协同，不直接操作账号</div></div><div className="mt-6 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-7">{days.map(day => { const matching = scheduledItems.filter(item => item.scheduledAt && dateKey(new Date(item.scheduledAt)) === dateKey(day)); return <div key={day.toISOString()} className={`min-h-36 rounded-2xl border p-3 ${dateKey(day) === dateKey(new Date()) ? "border-[#D9B0A2] bg-[#FCF2EE]" : "border-[#ECE5DE] bg-[#FFFEFC]"}`}><p className="text-[11px] text-[#9A8E84]">{day.toLocaleDateString("zh-CN", { weekday: "short" })}</p><p className="mt-1 font-serif text-lg text-[#51453E]">{day.getDate()}</p><div className="mt-3 space-y-2">{matching.map(item => <button key={item.id} onClick={() => setPublishId(item.id)} className="w-full rounded-lg bg-[#F0E2DB] px-2 py-1.5 text-left text-[11px] leading-4 text-[#814C40]"><span className="block truncate font-medium">{item.title}</span><span className="block truncate opacity-75">{item.themeName}</span></button>)}{!matching.length && <p className="pt-2 text-[11px] text-[#B1A69E]">留白</p>}</div></div>; })}</div></section>
    <section className="grid gap-6 xl:grid-cols-[0.9fr_1.1fr]"><div className="rounded-[1.5rem] border border-[#E9E1D9] bg-[#FFFDFC] p-5 sm:p-6"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#E9F1EB] text-[#568168]"><CalendarCheck2 className="h-4 w-4" /></span><div><p className="font-serif text-lg text-[#413632]">写入发布排期</p><p className="text-xs text-[#948980]">排期由你确认后生效。</p></div></div><div className="mt-5 space-y-3"><select value={selectedId} onChange={event => setSelectedId(event.target.value)} className="h-10 w-full rounded-md border border-[#E7DED6] bg-[#FFFEFC] px-3 text-sm text-[#5F554F]"><option value="">选择一篇内容</option>{readyItems.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select><Input type="date" value={scheduleDate} onChange={event => setScheduleDate(event.target.value)} className="border-[#E7DED6] bg-[#FFFEFC]" /><Button onClick={() => selectedId && schedule.mutate({ id: Number(selectedId), scheduledAt: new Date(`${scheduleDate}T09:00:00`) })} disabled={schedule.isPending || !selectedId} className="w-full rounded-xl bg-[#8E5547] text-white hover:bg-[#754336]"><CalendarCheck2 className="mr-2 h-4 w-4" />确认排期</Button></div></div>
      <div className="rounded-[1.5rem] border border-[#E9E1D9] bg-[#FFFDFC] p-5 sm:p-6"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#F9EEE3] text-[#A76A44]"><ClipboardCheck className="h-4 w-4" /></span><div><p className="font-serif text-lg text-[#413632]">发布前检查</p><p className="text-xs text-[#948980]">不代替你的最终判断。</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{["标题与首屏表达清楚", "封面重点与正文一致", "标签、引用与素材已核对", "发布时段和互动跟进已安排"].map(item => <label key={item} className="flex cursor-pointer items-center gap-2.5 rounded-xl bg-[#F8F4EF] px-3 py-3 text-sm text-[#655A53]"><input type="checkbox" className="h-4 w-4 accent-[#96604F]" />{item}</label>)}</div><div className="mt-5 rounded-xl border border-dashed border-[#DECAC0] bg-[#FEF9F6] p-3 text-xs leading-5 text-[#80685D]"><ShieldCheck className="mr-1 inline h-3.5 w-3.5 text-[#A86A58]" />发布动作仅由你在小红书官方客户端或官方认可的入口中完成；此处只保存协作状态和结果。</div></div></section>
    <section className="rounded-[1.5rem] border border-[#E9E1D9] bg-[#FFFDFC] p-5 sm:p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-xs font-medium tracking-[0.15em] text-[#A49A91]">MANUAL PUBLISH LOG</p><h2 className="mt-1 font-serif text-xl text-[#413632]">登记人工发布结果</h2></div>{selectedPublish && <StatusPill status={selectedPublish.status as ContentStatusKey} />}</div><div className="mt-5 grid gap-3 lg:grid-cols-[1fr_1fr_1.4fr_auto]"><select value={publishId ?? ""} onChange={event => setPublishId(event.target.value ? Number(event.target.value) : null)} className="h-10 rounded-md border border-[#E7DED6] bg-[#FFFEFC] px-3 text-sm text-[#5F554F]"><option value="">选择已排期内容</option>{scheduledItems.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select><Input value={publishUrl} onChange={event => setPublishUrl(event.target.value)} placeholder="发布链接（可选）" className="border-[#E7DED6] bg-[#FFFEFC]" /><Textarea value={publishResult} onChange={event => setPublishResult(event.target.value)} placeholder="记录发布时间、执行情况、需要跟进的事项" className="min-h-10 border-[#E7DED6] bg-[#FFFEFC]" /><Button onClick={() => publishId && markPublished.mutate({ id: publishId, publishResult, publishedUrl: publishUrl })} disabled={markPublished.isPending || !publishId} className="h-10 rounded-xl bg-[#4F7A60] text-white hover:bg-[#3F654E]"><Send className="mr-2 h-4 w-4" />确认已发布</Button></div><p className="mt-3 flex items-center gap-2 text-xs text-[#93877E]"><CheckCircle2 className="h-3.5 w-3.5 text-[#5C886C]" />登记后，这篇内容会进入运营复盘，等待录入真实表现数据。</p></section>
  </div>;
}

function CalendarState({ title, description, retry }: { title: string; description: string; retry?: () => void }) { return <div className="mx-auto flex min-h-[60vh] max-w-7xl items-center justify-center"><div className="max-w-lg rounded-[1.75rem] border border-[#E9E1D9] bg-[#FFFDFC] p-9 text-center"><p className="text-xs font-medium tracking-[0.18em] text-[#A56F61]">PUBLISHING COORDINATION</p><h1 className="mt-3 font-serif text-2xl text-[#443732]">{title}</h1><p className="mt-3 text-sm leading-6 text-[#8B8077]">{description}</p>{retry ? <Button onClick={retry} variant="outline" className="mt-6 rounded-xl border-[#DCC9BE] text-[#8E5547] hover:bg-[#FBF3EF]">重新载入</Button> : <div className="mx-auto mt-6 h-1.5 w-24 animate-pulse rounded-full bg-[#E8D2C9]" />}</div></div>; }
