import { StatusPill, type ContentStatusKey } from "@/components/StatusPill";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Check, Lightbulb, Plus, Sparkles, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

const emptyStrategy = { accountName: "", positioning: "", targetAudience: "", corePromise: "", brandVoice: "" };
const emptyIdea = { title: "", themeName: "", brief: "", contentType: "教程" as const };

export default function Library() {
  const utils = trpc.useUtils();
  const strategyQuery = trpc.strategy.get.useQuery();
  const themesQuery = trpc.themes.list.useQuery();
  const contentQuery = trpc.content.list.useQuery();
  const [strategy, setStrategy] = useState(emptyStrategy);
  const [idea, setIdea] = useState(emptyIdea);
  const [themeForm, setThemeForm] = useState({ name: "", description: "", audienceNeed: "" });
  useEffect(() => { if (strategyQuery.data) setStrategy({ accountName: strategyQuery.data.accountName, positioning: strategyQuery.data.positioning, targetAudience: strategyQuery.data.targetAudience, corePromise: strategyQuery.data.corePromise, brandVoice: strategyQuery.data.brandVoice }); }, [strategyQuery.data]);
  const saveStrategy = trpc.strategy.save.useMutation({ onSuccess: () => { utils.strategy.get.invalidate(); toast.success("账号策略已保存"); }, onError: () => toast.error("保存失败，请检查后重试") });
  const createTheme = trpc.themes.create.useMutation({ onSuccess: () => { utils.themes.list.invalidate(); setThemeForm({ name: "", description: "", audienceNeed: "" }); toast.success("已加入技能主题"); }, onError: () => toast.error("主题信息还不完整") });
  const deleteTheme = trpc.themes.delete.useMutation({ onSuccess: () => utils.themes.list.invalidate() });
  const createIdea = trpc.content.create.useMutation({ onSuccess: () => { utils.content.list.invalidate(); utils.content.overview.invalidate(); setIdea(emptyIdea); toast.success("选题已存入内容库"); }, onError: () => toast.error("请完善选题标题和主题") });
  const saveIdea = () => createIdea.mutate({ themeId: null, themeName: idea.themeName || "未归类", contentType: idea.contentType, status: "idea", title: idea.title, brief: idea.brief, body: "", tags: "", coverPoints: "", assetNotes: "", reviewNotes: "" });

  if (strategyQuery.isLoading || themesQuery.isLoading || contentQuery.isLoading) return <WorkspaceState eyebrow="SKILL CONTENT LIBRARY" title="正在展开你的内容资产" description="正在载入账号定位、技能主题与选题池。" />;
  if (strategyQuery.error || themesQuery.error || contentQuery.error) return <WorkspaceState eyebrow="SKILL CONTENT LIBRARY" title="内容库暂时未能载入" description="请检查网络后重试；你的既有内容不会因此丢失。" retry={() => { strategyQuery.refetch(); themesQuery.refetch(); contentQuery.refetch(); }} />;

  return <div className="mx-auto max-w-7xl space-y-6"><header><p className="text-xs font-medium tracking-[0.18em] text-[#A56F61]">SKILL CONTENT LIBRARY</p><h1 className="mt-2 font-serif text-3xl text-[#403530]">内容库</h1><p className="mt-2 text-sm text-[#82776E]">先对齐账号的表达，再把灵感沉淀为可持续推进的内容资产。</p></header>
    <section className="grid gap-6 xl:grid-cols-[1.18fr_0.82fr]"><div className="rounded-[1.5rem] border border-[#E9E1D9] bg-[#FFFDFC] p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-medium tracking-[0.15em] text-[#A49A91]">ACCOUNT STRATEGY</p><h2 className="mt-1 font-serif text-xl text-[#413632]">账号定位卡</h2></div><Sparkles className="h-5 w-5 text-[#B6705E]" /></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="账号名称" value={strategy.accountName} onChange={accountName => setStrategy({ ...strategy, accountName })} placeholder="例如：你的 Skill 账号名" /><Field label="核心定位" value={strategy.positioning} onChange={positioning => setStrategy({ ...strategy, positioning })} placeholder="你希望被谁因何事记住？" textarea /><Field label="目标受众" value={strategy.targetAudience} onChange={targetAudience => setStrategy({ ...strategy, targetAudience })} placeholder="他们正处在哪个阶段？" textarea /><Field label="内容承诺" value={strategy.corePromise} onChange={corePromise => setStrategy({ ...strategy, corePromise })} placeholder="关注后可以稳定获得什么？" textarea /><div className="sm:col-span-2"><Field label="表达语气与边界" value={strategy.brandVoice} onChange={brandVoice => setStrategy({ ...strategy, brandVoice })} placeholder="例如：真诚、具体、克制；不制造焦虑。" textarea /></div></div><div className="mt-5 flex justify-end"><Button onClick={() => saveStrategy.mutate(strategy)} disabled={saveStrategy.isPending} className="rounded-xl bg-[#8E5547] text-white hover:bg-[#754336]"><Check className="mr-2 h-4 w-4" />保存定位</Button></div></div>
      <div className="rounded-[1.5rem] border border-[#E9E1D9] bg-[#FFFDFC] p-5 sm:p-6"><div><p className="text-xs font-medium tracking-[0.15em] text-[#A49A91]">SKILL PILLARS</p><h2 className="mt-1 font-serif text-xl text-[#413632]">技能主题</h2></div><div className="mt-5 space-y-3">{themesQuery.data?.length ? themesQuery.data.map(theme => <div key={theme.id} className="group rounded-xl border border-[#EEE7E0] p-3.5"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-medium text-[#514640]">{theme.name}</p><p className="mt-1 text-xs leading-5 text-[#877B72]">{theme.description}</p></div><button onClick={() => deleteTheme.mutate({ id: theme.id })} className="opacity-0 transition-opacity group-hover:opacity-100 text-[#B28C81] hover:text-[#A34F42]" aria-label="删除主题"><Trash2 className="h-4 w-4" /></button></div></div>) : <p className="rounded-xl bg-[#F8F4EF] p-4 text-sm leading-6 text-[#958A81]">尚未创建主题。先定义一到三个能长期深耕的 Skill 内容支柱。</p>}</div><div className="mt-5 space-y-2"><Input value={themeForm.name} onChange={event => setThemeForm({ ...themeForm, name: event.target.value })} placeholder="主题名称，例如：AI 工作流" className="border-[#E7DED6] bg-[#FFFEFC]" /><Textarea value={themeForm.description} onChange={event => setThemeForm({ ...themeForm, description: event.target.value })} placeholder="这个主题会覆盖什么？" className="min-h-16 border-[#E7DED6] bg-[#FFFEFC]" /><Input value={themeForm.audienceNeed} onChange={event => setThemeForm({ ...themeForm, audienceNeed: event.target.value })} placeholder="受众核心需求" className="border-[#E7DED6] bg-[#FFFEFC]" /><Button variant="outline" onClick={() => createTheme.mutate(themeForm)} disabled={createTheme.isPending} className="w-full rounded-xl border-[#DCC9BE] text-[#8E5547] hover:bg-[#FBF3EF]"><Plus className="mr-2 h-4 w-4" />添加主题</Button></div></div></section>
    <section className="grid gap-6 xl:grid-cols-[0.78fr_1.22fr]"><div className="rounded-[1.5rem] border border-[#E9E1D9] bg-[#FFFDFC] p-5 sm:p-6"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#F7E9E2] text-[#A8624E]"><Lightbulb className="h-4 w-4" /></span><div><p className="font-serif text-lg text-[#413632]">捕捉一个新灵感</p><p className="text-xs text-[#948980]">先记录，再决定是否投入生产。</p></div></div><div className="mt-5 space-y-3"><Input value={idea.title} onChange={event => setIdea({ ...idea, title: event.target.value })} placeholder="选题标题或问题" className="border-[#E7DED6] bg-[#FFFEFC]" /><div className="grid grid-cols-2 gap-3"><Input value={idea.themeName} onChange={event => setIdea({ ...idea, themeName: event.target.value })} placeholder="所属主题" className="border-[#E7DED6] bg-[#FFFEFC]" /><select value={idea.contentType} onChange={event => setIdea({ ...idea, contentType: event.target.value as typeof idea.contentType })} className="h-9 rounded-md border border-[#E7DED6] bg-[#FFFEFC] px-3 text-sm text-[#5F554F]"><option>教程</option><option>清单</option><option>案例</option><option>观点</option><option>复盘</option></select></div><Textarea value={idea.brief} onChange={event => setIdea({ ...idea, brief: event.target.value })} placeholder="为什么值得写？准备给读者带走什么？" className="min-h-28 border-[#E7DED6] bg-[#FFFEFC]" /><Button onClick={saveIdea} disabled={createIdea.isPending} className="w-full rounded-xl bg-[#8E5547] text-white hover:bg-[#754336]"><Plus className="mr-2 h-4 w-4" />存入选题池</Button></div></div>
      <div className="rounded-[1.5rem] border border-[#E9E1D9] bg-[#FFFDFC] p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-medium tracking-[0.15em] text-[#A49A91]">IDEA RESERVE</p><h2 className="mt-1 font-serif text-xl text-[#413632]">正在积累的内容</h2></div><span className="rounded-full bg-[#F4EEE8] px-3 py-1 text-xs text-[#796E65]">{contentQuery.data?.length ?? 0} 条</span></div><div className="mt-5 divide-y divide-[#EEE8E2]">{contentQuery.data?.length ? contentQuery.data.map(item => <div key={item.id} className="flex items-center gap-3 py-3.5 first:pt-0"><StatusPill status={item.status as ContentStatusKey} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-[#504540]">{item.title}</p><p className="mt-1 truncate text-xs text-[#948980]">{item.themeName} · {item.contentType}{item.brief ? ` · ${item.brief}` : ""}</p></div></div>) : <div className="py-12 text-center text-sm text-[#9A8F85]">内容库还没有选题。用左侧表单记录第一个灵感。</div>}</div></div></section>
  </div>;
}

function Field({ label, value, onChange, placeholder, textarea = false }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; textarea?: boolean }) { return <label className="block"><span className="mb-1.5 block text-xs font-medium text-[#756A62]">{label}</span>{textarea ? <Textarea value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} className="min-h-24 border-[#E7DED6] bg-[#FFFEFC] text-sm" /> : <Input value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} className="border-[#E7DED6] bg-[#FFFEFC] text-sm" />}</label>; }

function WorkspaceState({ eyebrow, title, description, retry }: { eyebrow: string; title: string; description: string; retry?: () => void }) { return <div className="mx-auto flex min-h-[60vh] max-w-7xl items-center justify-center"><div className="w-full max-w-lg rounded-[1.75rem] border border-[#E9E1D9] bg-[#FFFDFC] p-9 text-center shadow-[0_12px_40px_rgba(79,59,48,0.04)]"><p className="text-xs font-medium tracking-[0.18em] text-[#A56F61]">{eyebrow}</p><h1 className="mt-3 font-serif text-2xl text-[#443732]">{title}</h1><p className="mt-3 text-sm leading-6 text-[#8B8077]">{description}</p>{retry ? <Button onClick={retry} variant="outline" className="mt-6 rounded-xl border-[#DCC9BE] text-[#8E5547] hover:bg-[#FBF3EF]">重新载入</Button> : <div className="mx-auto mt-6 h-1.5 w-24 overflow-hidden rounded-full bg-[#F3E5DF]"><div className="h-full w-2/3 animate-pulse rounded-full bg-[#B56E5C]" /></div>}</div></div>; }
